#!/usr/bin/env ruby
# frozen_string_literal: true
#
# coverage.rb — deterministic content-coverage map for the Gardener.
#
# Reads the content library (_data/stories.yml, _data/wordgames.yml) and prints
# a Markdown coverage matrix of age_band x Galinsky-7 skill, plus the single
# biggest gap. The Gardener workflow pipes this into Claude's context so the
# "fill a gap" decision is grounded in a computed fact, not a guess.
#
# Pure read-only. No network, no writes. Run: `ruby .github/gardener/coverage.rb`

require "yaml"
require "set"

ROOT   = File.expand_path("../..", __dir__)
BANDS  = %w[6-12m 12-24m 2-3y 3-4y 4-5y].freeze
SKILLS = %w[focus perspective communicating connections
            critical-thinking challenges self-directed].freeze

def load_list(path)
  full = File.join(ROOT, path)
  return [] unless File.exist?(full)
  data = YAML.safe_load(File.read(full), permitted_classes: [], aliases: false)
  data.is_a?(Array) ? data.compact : []
end

stories = load_list("_data/stories.yml")
games   = load_list("_data/wordgames.yml")
items   = stories.map { |s| s.merge("_kind" => "story") } +
          games.map   { |g| g.merge("_kind" => "game") }

# counts[band][skill] = number of content pieces covering that cell
counts   = Hash.new { |h, b| h[b] = Hash.new(0) }
untagged = []
items.each do |it|
  bands  = Array(it["age_band"])
  skills = Array(it["skills"])
  if bands.empty? || skills.empty?
    untagged << "#{it['_kind']}:#{it['id']} (age_band=#{bands.inspect}, skills=#{skills.inspect})"
    next
  end
  bands.each { |b| skills.each { |s| counts[b][s] += 1 } }
end

col_w = SKILLS.map(&:length).max
pad   = ->(s, w) { s.to_s.ljust(w) }

puts "# Content coverage matrix (age_band x Galinsky-7)"
puts
puts "Generated by `.github/gardener/coverage.rb`. Each cell = number of stories"
puts "+ word-games tagged with BOTH that age band and that skill."
puts "Library: #{stories.size} stories, #{games.size} word-games (#{items.size} total)."
puts

# header
header = "| " + pad.call("age_band", 8) + " | " +
         SKILLS.map { |s| pad.call(s, col_w) }.join(" | ") + " |"
sep    = "|-" + "-" * 8 + "-|-" +
         SKILLS.map { "-" * col_w }.join("-|-") + "-|"
puts header
puts sep
BANDS.each do |b|
  row = "| " + pad.call(b, 8) + " | " +
        SKILLS.map { |s| pad.call(counts[b][s], col_w) }.join(" | ") + " |"
  puts row
end
puts

# --- Gaps: empty cells, ranked. Bias toward the youngest served band first,
#     since the little one is ~1yr (12-24m) today. ---
band_rank = BANDS.each_with_index.to_h
empty = []
BANDS.each { |b| SKILLS.each { |s| empty << [b, s] if counts[b][s].zero? } }

# A skill with ZERO coverage in any band is the loudest gap.
skill_totals = SKILLS.map { |s| [s, BANDS.sum { |b| counts[b][s] }] }.to_h
zero_skills  = SKILLS.select { |s| skill_totals[s].zero? }

puts "## Skill totals (across all bands)"
SKILLS.sort_by { |s| skill_totals[s] }.each do |s|
  flag = skill_totals[s].zero? ? "  <-- NO CONTENT" : ""
  puts "- #{pad.call(s, col_w)} : #{skill_totals[s]}#{flag}"
end
puts

unless untagged.empty?
  puts "## Untagged content (missing age_band or skills — cannot be placed)"
  untagged.each { |u| puts "- #{u}" }
  puts
end

# Pick THE biggest gap for the Gardener to consider.
biggest =
  if !zero_skills.empty?
    # whole skill missing: pair it with the currently-served band (12-24m if
    # present in the library, else the youngest band that has any content).
    served = BANDS.select { |b| SKILLS.any? { |s| counts[b][s] > 0 } }
    band   = served.include?("12-24m") ? "12-24m" : (served.first || "12-24m")
    skill  = zero_skills.min_by { |s| SKILLS.index(s) }
    [band, skill, "skill has zero content anywhere"]
  elsif !empty.empty?
    b, s = empty.min_by { |bb, _| band_rank[bb] }
    [b, s, "empty cell"]
  end

puts "## Biggest gap (the Gardener's default 'fill a gap' target)"
if biggest
  b, s, why = biggest
  puts "**age_band `#{b}` x skill `#{s}`** — #{why}."
  puts
  puts "If choosing option (b) fill-a-gap, write ONE new story or word-game tagged"
  puts "`age_band: [#{b}]` and including `#{s}` in its `skills:` — in the house style,"
  puts "using only existing art keys. Doing nothing is still valid if a higher-value"
  puts "ingest or tend task exists."
else
  puts "No empty cells — every age_band x skill pair has at least one piece of content."
  puts "Prefer an ingest or tend task this run."
end
